services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    restart: always
    dns:
      - 8.8.8.8
      - 8.8.4.4
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - NODE_ENV=production
      - WEBHOOK_URL=http://localhost:5678/
      - N8N_CORS_ALLOWED_ORIGINS=*
      - EXECUTIONS_DATA_PRUNE=true
      - EXECUTIONS_DATA_MAX_AGE=168
    volumes:
      - C:/Users/mateo/Desktop/Archivos/n8n-docker/n8n_data:/home/node/.n8n
